version: '3'

services:
  node1:
    build:
      context: .
      dockerfile: ./node.Dockerfile

  node2:
    build:
      context: .
      dockerfile: ./node.Dockerfile

  node3:
    build:
      context: .
      dockerfile: ./node.Dockerfile

  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    ports:
      - '83:80'
